Added base region layout
RAnLabNL/RAnLab-frontend pull request #21
Opened 2020-09-13 14:46 UTC by lesleychard

Resolves #12 

- Added responsive top and left navigation
- Implemented Material UI x Next JS config to fix hot reload issues
- Added advanced `color` helpers
- A start to some theme configs (mostly palettes)
- Added a VS Code snippet for creating react components

2020-09-13 15:58 UTC, lesleychard commented on components/Logo.tsx
> +Logo.defaultProps = {
I realize this needs to go - updating this PR shortly

2020-09-22 23:41 UTC, whymarrh requested changes
Two small things:

- Can we add `.vscode/` to the `.gitignore`?
- Can we move the `@types/` packages to dev deps?

2020-09-23 00:50 UTC, lesleychard commented
> Two small things:
> 
> * Can we add `.vscode/` to the `.gitignore`?
> * Can we move the `@types/` packages to dev deps?

We can, on both accounts. I left the `.vscode` in there because I thought the snippet I added for react components would come in handy for future development 🤷‍♀️

2020-09-23 01:02 UTC, lesleychard commented
@whymarrh Should be good now.

2020-09-23 01:04 UTC, whymarrh submitted a review, later dismissed
LGTM! Re: the VS Code files, I believe we can force add individual files as needed, adding the directory to the ignore list should prevent us from inadvertently adding files.

2020-09-23 22:46 UTC, lesleychard commented
@whymarrh You good with this one now? I'll add the snippet back in if I feel we need it.

2020-09-24 16:45 UTC, whymarrh approved these changes
LGTM!

2020-09-26 13:43 UTC, merged